# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  apple-font = {
    pname = "apple-font";
    version = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
    src = fetchTarball {
      url = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
      sha256 = "sha256-SeTLhl6iFkCDowM87/BTa3mnknngjKpwY89wx8rOQGU=";
    };
  };
  apple-font-emoji = {
    pname = "apple-font-emoji";
    version = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  grubTheme = {
    pname = "grubTheme";
    version = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "grub2-theme";
      rev = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
      fetchSubmodules = false;
      sha256 = "sha256-ChnML4zm4EnVX/WmZW5RWHnK/tqjXSeR4BK8XfN0xxA=";
    };
    date = "2026-01-11";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "ae647cef5b3c3dd52bedd7a8c881988e412a2dca";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "ae647cef5b3c3dd52bedd7a8c881988e412a2dca";
      fetchSubmodules = false;
      sha256 = "sha256-ImJeI5xbd/w4nchFwc0tSS8v2vYWx/ttwM5uk2BWsCk=";
    };
    date = "2026-04-23";
  };
  tmuxFloax = {
    pname = "tmuxFloax";
    version = "133f526793d90d2caa323c47687dd5544a2c704b";
    src = fetchFromGitHub {
      owner = "omerxx";
      repo = "tmux-floax";
      rev = "133f526793d90d2caa323c47687dd5544a2c704b";
      fetchSubmodules = false;
      sha256 = "sha256-9Hb9dn2qHF6KcIhtogvycX3Z0MoQrLPLCzZXtjGlPHw=";
    };
    date = "2026-02-24";
  };
}
