# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  grubTheme = {
    pname = "grubTheme";
    version = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "grub2-theme";
      rev = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
      fetchSubmodules = false;
      sha256 = "sha256-ChnML4zm4EnVX/WmZW5RWHnK/tqjXSeR4BK8XfN0xxA=";
    };
    date = "2026-01-11";
  };
  kitty = {
    pname = "kitty";
    version = "dc29e102cc44a8d121a90af35637e0b1b642e7c4";
    src = fetchFromGitHub {
      owner = "kovidgoyal";
      repo = "kitty";
      rev = "dc29e102cc44a8d121a90af35637e0b1b642e7c4";
      fetchSubmodules = false;
      sha256 = "sha256-FVMhZsKIeb2WzhqIEQAOy+vhT8r2saFkvxbxbfeeXic=";
    };
    date = "2026-04-27";
  };
  tmuxFloax = {
    pname = "tmuxFloax";
    version = "133f526793d90d2caa323c47687dd5544a2c704b";
    src = fetchFromGitHub {
      owner = "omerxx";
      repo = "tmux-floax";
      rev = "133f526793d90d2caa323c47687dd5544a2c704b";
      fetchSubmodules = false;
      sha256 = "sha256-9Hb9dn2qHF6KcIhtogvycX3Z0MoQrLPLCzZXtjGlPHw=";
    };
    date = "2026-02-24";
  };
}
