[all_follow]
flake-compat = "flake-compat"
flake-utils = "flake-utils"
nixpkgs = "nixpkgs"
rust-overlay = "rust-overlay"
systems = "systems"
treefmt-nix = "treefmt-nix"

[inputs.app2unit]
type = "fetch"
url = "gh:Vladimir-csp/app2unit"

[inputs.apple-font-emoji]
type = "fixed"
url = "https://github.com/samuelngs/apple-emoji-ttf/releases/download/macos-26-20260613-f1fc560b/AppleColorEmoji-Linux.ttf"

[inputs.base16]
url = "gh:SenchoPens/base16.nix"

[inputs.cliphist]
type = "fetch"
url = "gh:sentriz/cliphist"

[inputs.cliphist-tui]
type = "fetch"
url = "gh:SHORiN-KiWATA/cliphist-tui"

[inputs.confirm-dialog]
type = "fetch"
url = "gh:onelocked/confirm-dialog.yazi"

[inputs.disko]
url = "gh:nix-community/disko"

[inputs.extra-metadata]
type = "fetch"
url = "gh:boydaihungst/file-extra-metadata.yazi"

[inputs.fsel]
type = "fetch"
url = "gh:Mjoyufull/fsel"

[inputs.fuzzy-search]
type = "fetch"
url = "gh:onelocked/fuzzy-search.yazi"

[inputs.helium-browser]
url = "gh:amaanq/helium-flake"

[inputs.hjem]
url = "gh:feel-co/hjem"

[inputs.hypr-plugs]
type = "fetch"
url = "gh:hyprwm/hyprland-plugins"

[inputs.hyprland]
exclude_follow = ["nixpkgs"]
url = "gh:hyprwm/Hyprland/79bc0ca16e7cca40c247a9200634d150fa8193d1"

[inputs.lan-mouse]
type = "fetch"
url = "gh:feschber/lan-mouse"

[inputs.nixos-core]
url = "gh:manic-systems/nixos-core"

[inputs.nixos-hardware]
url = "gh:NixOS/nixos-hardware"

[inputs.nixpkgs]
url = "gh:nixos/nixpkgs/nixos-unstable"

[inputs.no-header-prompt]
type = "fetch"
url = "gh:onelocked/no-header-prompt.yazi"

[inputs.otter-launcher]
type = "fetch"
url = "gh:kuokuo123/otter-launcher"

[inputs.preservation]
url = "gh:nix-community/preservation"

[inputs.quickshell]
url = "gh:quickshell-mirror/quickshell"

[inputs.scroll-overview]
type = "fetch"
url = "gh:yayuuu/hyprland-scroll-overview"

[inputs.sf-compact]
type = "fixed"
url = "https://devimages-cdn.apple.com/design/resources/download/SF-Compact.dmg"

[inputs.sf-mono]
type = "fixed"
url = "https://devimages-cdn.apple.com/design/resources/download/SF-Mono.dmg"

[inputs.sf-pro]
type = "fixed"
url = "https://devimages-cdn.apple.com/design/resources/download/SF-Pro.dmg"

[inputs.sops-nix]
url = "gh:Mic92/sops-nix"

[inputs.spicetify-nix]
url = "gh:Gerg-L/spicetify-nix"

[inputs.systemctl-tui]
type = "fetch"
url = "gh:rgwood/systemctl-tui"

[inputs.systems]
url = "gh:nix-systems/default-linux"

[inputs.tack]
url = "gh:manic-systems/tack"

[inputs.theme-store]
type = "fetch"
url = "gh:zen-browser/theme-store"

[inputs.tmuxFloax]
type = "fetch"
url = "gh:omerxx/tmux-floax"

[inputs.tuishell]
type = "fetch"
url = "git+https://gitea.onelock.org/onelock/tuishell"

[inputs.vimmax]
url = "gh:onelocked/vimmax"

[inputs.yazi]
url = "gh:sxyazi/yazi"

[inputs.yazi-plugins]
type = "fetch"
url = "gh:AminurAlam/yazi-plugins"

[inputs.yaziline]
type = "fetch"
url = "gh:llanosrocas/yaziline.yazi"

[inputs.zen-browser]
url = "gh:0xc000022070/zen-browser-flake"

[shorturls]
gh = "github:{path}"
