{
  perSystem =
    { pkgs, constants, ... }:
    {
      legacyPackages.remote-install = pkgs.writeShellApplication {
        name = "remote-install";
        runtimeInputs = with pkgs; [
          gum
          rsync
          jq
          openssh
          gnused
          coreutils
        ];

        text = ''
          clear
          gum style \
            --foreground 212 --border-foreground 212 --border double \
            --align center --width 50 --margin "1 2" --padding "1 2" \
            "NixOS Anywhere Deployer"

          # prompt for the target ip
          echo "Enter target connection string:"
          TARGET_IP=$(gum input --placeholder "root@192.168.1.100" --value "root@")
          if [ -z "$TARGET_IP" ] || [ "$TARGET_IP" = "root@" ]; then
            gum style --foreground 196 "Error: Target IP is required."
            exit 1
          fi

          # select nixosConfiguration host
          echo "Parsing flake for NixOS configurations..."
          HOSTS=$(nix eval .#nixosConfigurations --apply builtins.attrNames --json --extra-experimental-features "nix-command flakes" | jq -r '.[]' || true)

          if [ -z "$HOSTS" ]; then
            gum style --foreground 214 "Warning: Could not automatically detect configurations."
            echo "Enter the flake host (e.g., gaming-pc):"
            HOST=$(gum input --placeholder "gaming-pc")
          else
            echo "Select the target NixOS configuration:"
            HOST=$(echo "$HOSTS" | gum choose)
          fi

          if [ -z "$HOST" ]; then
            gum style --foreground 196 "Error: Flake host is required."
            exit 1
          fi

          # grab hardware configuration
          if gum confirm "Do you want to fetch and install hardware-configuration.nix?" --default=false; then
            gum style --foreground 82 "Fetching hardware configuration from $TARGET_IP for host '$HOST'..."
            echo ""

            RAW_CONFIG=$(ssh -o StrictHostKeyChecking=no -T "$TARGET_IP" "nixos-generate-config --no-filesystems --show-hardware-config")

            if [ -z "$RAW_CONFIG" ]; then
              gum style --foreground 196 "Error: Failed to fetch configuration."
              exit 1
            fi

            FORMATTED_CONFIG=$(echo "$RAW_CONFIG" | sed -e 's/^/    /' -e '$ s/}/};/')

            OUT_DIR="./hosts/$HOST/hardware"
            OUT_FILE="$OUT_DIR/hardware-configuration.nix"
            mkdir -p "$OUT_DIR"

            {
              echo "# Auto-generated by fetch-hardware-config"
              echo "{"
              echo "  exo.hardware.\"$HOST\" ="
              echo "$FORMATTED_CONFIG"
              echo "}"
            } > "$OUT_FILE"

            gum style --margin "1 0" --foreground 82 "Successfully saved to $OUT_FILE"
            cat "$OUT_FILE"
            echo ""

            if ! gum confirm "Continue with remote install?"; then
              echo "Exiting."
              exit 0
            fi
          fi

          # deployment phase
          echo "Select execution phases (Space to toggle, Enter to confirm):"
          PHASES_RAW=$(gum choose --no-limit --selected "kexec,disko,install,reboot" "kexec" "disko" "install" "reboot")
          if [ -z "$PHASES_RAW" ]; then
            gum style --foreground 196 "Error: At least one phase must be selected."
            exit 1
          fi
          PHASES=$(echo "$PHASES_RAW" | tr '\n' ',' | sed 's/,$//')

          gum style --margin "1 0" --foreground 82 "Configuration complete!"
          echo "Target: $TARGET_IP"
          echo "Phases: $PHASES"
          echo "Host:   $HOST"
          echo ""

          if ! gum confirm "Ready to deploy?"; then
            echo "Aborting."
            exit 0
          fi

          # getting the sops age key ready
          echo "Staging age key..."
          STAGING_DIR=$(mktemp -d)
          trap 'rm -rf "$STAGING_DIR"' EXIT

          KEY_PATH="${constants.homedir}/.config/sops/age/keys.txt"
          TARGET_DIR="$STAGING_DIR/persist${constants.homedir}/.config/sops/age"

          mkdir -p "$TARGET_DIR"
          rsync -av "$KEY_PATH" "$TARGET_DIR/keys.txt"
          chmod 600 "$TARGET_DIR/keys.txt"

          # run nixos-anywhere
          echo "Running nixos-anywhere..."
          nix run github:nix-community/nixos-anywhere -- \
            --phases "$PHASES" \
            --extra-files "$STAGING_DIR" \
            --chown /persist${constants.homedir}/.config/sops/age/keys.txt 1000:100 \
            --build-on local \
            --flake .#"$HOST" \
            "$TARGET_IP"
        '';
      };
    };
}
