{
  inputs,
  lib,
  self,
  ...
}:
{
  ff.zen-browser = {
    url = "github:0xc000022070/zen-browser-flake";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  m.zen-browser =
    { pkgs, config, ... }:
    let
      cfg = config.custom.programs.zen-browser;

      mkLockedAttrs = builtins.mapAttrs (
        _: value: {
          Value = value;
          Status = "locked";
        }
      );

      unwrapped =
        inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.twilight-unwrapped.override
          {
            inherit (cfg) policies;
          };

      wrapped = (pkgs.wrapFirefox unwrapped { }).override {
        inherit (cfg) extraPrefs nativeMessagingHosts;
      };

      # Generate user.js content from profile settings
      mkUserJs =
        settings:
        settings
        |> lib.mapAttrsToList (name: value: ''user_pref("${name}", ${builtins.toJSON value});'')
        |> lib.concatStringsSep "\n";

      profilesCfg = cfg.profiles;

      # Mods activation script (runs at system activation)
      modsActivationScript =
        profileName: profile:
        let
          mods = profile.mods;
          profilePath = "${config.hj.xdg.config.directory}/zen/${profile.path}";
        in
        pkgs.writeShellScript "zen-mods-update-${profileName}" ''
          THEMES_FILE="${profilePath}/zen-themes.json"
          MODS="${lib.concatStringsSep " " mods}"
          BASE_DIR="${profilePath}"
          MANAGED_FILE="$BASE_DIR/zen-mods-nix-managed.json"

          # ensure profile dir exists
          mkdir -p "$BASE_DIR/chrome/zen-themes"

          if [ ! -f "$THEMES_FILE" ]; then
            echo '{}' > "$THEMES_FILE"
          fi

          # Read current managed mods
          if [ -f "$MANAGED_FILE" ]; then
            CURRENT_MANAGED=$(${lib.getExe pkgs.jq} -r '.[]' "$MANAGED_FILE" 2>/dev/null || echo "")
          else
            CURRENT_MANAGED=""
          fi

          # Remove mods not in current list
          for uuid in $CURRENT_MANAGED; do
            if [[ " $MODS " != *" $uuid "* ]]; then
              ${lib.getExe pkgs.jq} "del(.[\"$uuid\"])" "$THEMES_FILE" > "$THEMES_FILE.tmp" && mv "$THEMES_FILE.tmp" "$THEMES_FILE"
              rm -rf "$BASE_DIR/chrome/zen-themes/$uuid"
              echo "Removed mod $uuid"
            fi
          done

          # Install/update current mods
          for mod_uuid in $MODS; do
            MOD_DIR="$BASE_DIR/chrome/zen-themes/$mod_uuid"
            if [ -d "$MOD_DIR" ]; then
              continue
            fi

            THEME_URL="https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/$mod_uuid/theme.json"
            echo "Fetching mod $mod_uuid from $THEME_URL"

            THEME_JSON=$(${lib.getExe pkgs.curl} -s "$THEME_URL")
            if [ $? -ne 0 ] || [ -z "$THEME_JSON" ]; then
              echo "Failed to fetch theme for mod $mod_uuid"
              continue
            fi

            if ! echo "$THEME_JSON" | ${lib.getExe pkgs.jq} empty 2>/dev/null; then
              echo "Invalid JSON for mod $mod_uuid"
              continue
            fi

            # Merge into themes file
            ${lib.getExe pkgs.jq} --arg uuid "$mod_uuid" --argjson theme "$THEME_JSON" '.[$uuid] = $theme' "$THEMES_FILE" > "$THEMES_FILE.tmp" && mv "$THEMES_FILE.tmp" "$THEMES_FILE"

            # Download mod files
            mkdir -p "$MOD_DIR"

            for file in chrome.css preferences.json readme.md; do
              FILE_URL="https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/$mod_uuid/$file"
              ${lib.getExe pkgs.curl} -s "$FILE_URL" -o "$MOD_DIR/$file" || true
            done
          done

          # Write new managed list
          echo "$MODS" | tr ' ' '\n' | ${lib.getExe pkgs.jq} -R -s 'split("\n") | map(select(. != ""))' > "$MANAGED_FILE"

          # Generate zen-themes.css
          ZEN_THEMES_CSS="$BASE_DIR/chrome/zen-themes.css"
          echo "/* Zen Mods - Generated by NixOS activation." > "$ZEN_THEMES_CSS"
          cat >> "$ZEN_THEMES_CSS" << 'EOFCSS'
          * DO NOT EDIT THIS FILE DIRECTLY!
          * Your changes will be overwritten.
          */
          EOFCSS

          # Get enabled mods
          ENABLED_MODS=$(${lib.getExe pkgs.jq} -r 'to_entries[] | select(.value.enabled == null or .value.enabled == true) | .key' "$THEMES_FILE")

          for mod_uuid in $ENABLED_MODS; do
            MOD_CSS="$BASE_DIR/chrome/zen-themes/$mod_uuid/chrome.css"
            if [ -f "$MOD_CSS" ]; then
              MOD_INFO=$(${lib.getExe pkgs.jq} -r ".\"$mod_uuid\" | \"/* Name: \(.name) */\\n/* Description: \(.description) */\\n/* Author: @\(.author) */\"" "$THEMES_FILE")
              echo "$MOD_INFO" >> "$ZEN_THEMES_CSS"
              cat "$MOD_CSS" >> "$ZEN_THEMES_CSS"
              echo "" >> "$ZEN_THEMES_CSS"
            fi
          done

          echo "/* End of Zen Mods */" >> "$ZEN_THEMES_CSS"

          if ! ${lib.getExe pkgs.jq} empty "$THEMES_FILE" 2>/dev/null; then
            echo "Error: Generated invalid JSON in $THEMES_FILE"
            exit 1
          fi
        '';
    in
    {
      custom.programs.zen-browser = {
        setAsDefaultBrowser = true;
        policies = {
          AutofillAddressEnabled = false;
          AutofillCreditCardEnabled = false;
          DisableAppUpdate = true;
          DisableFeedbackCommands = true;
          DisableFirefoxStudies = true;
          DisablePocket = true;
          DisableTelemetry = true;
          DontCheckDefaultBrowser = true;
          NoDefaultBookmarks = true;
          OfferToSaveLogins = false;
          PrintingEnabled = false;
          TranslateEnabled = false;
          SupportMenu = false;
          HardwareAcceleration = true;
          EnableTrackingProtection = {
            Value = true;
            Locked = true;
            Cryptomining = true;
            Fingerprinting = true;
          };
          Preferences = mkLockedAttrs {
            "media.hardware-video-decoding.force-enabled" = true;
            "media.rdd-ffmpeg.enabled" = true;
            "media.av1.enabled" = true;
            "gfx.x11-egl.force-enabled" = false;
            "widget.dmabuf.force-enabled" = true;

            "browser.tabs.warnOnClose" = false;
            "browser.aboutConfig.showWarning" = false;

            "xpinstall.signatures.required" = false;
            "toolkit.legacyUserProfileCustomizations.stylesheets" = true;

            "gfx.webrender.all" = true;

            "privacy.resistFingerprinting" = true;
            "privacy.resistFingerprinting.randomization.canvas.use_siphash" = true;
            "privacy.resistFingerprinting.randomization.daily_reset.enabled" = true;
            "privacy.resistFingerprinting.randomization.daily_reset.private.enabled" = true;
            "privacy.resistFingerprinting.block_mozAddonManager" = true;
            "privacy.spoof_english" = 1;

            "network.http.http3.enabled" = true;
            "network.socket.ip_addr_any.disabled" = true;

            "widget.use-xdg-desktop-portal.file-picker" = 1;

            "mousebutton.4th.enabled" = false;
            "mousebutton.5th.enabled" = false;
            "zen.welcome-screen.seen" = true;
            "zen.view.experimental-no-window-controls" = true;
            "zen.view.compact.hide-toolbar" = false;
            "zen.view.compact.hide-tabbar" = true;
            "middlemouse.paste" = false;
          };
          ExtensionSettings = {
            "{446900e4-71c2-419f-a6a7-df9c091e268b}" = {
              install_url = "https://addons.mozilla.org/firefox/downloads/file/4493940/bitwarden_password_manager-latest.xpi";
              installation_mode = "force_installed";
            };
            "uBlock0@raymondhill.net" = {
              install_url = "https://addons.mozilla.org/firefox/downloads/file/4458450/ublock_origin-latest.xpi";
              installation_mode = "force_installed";
            };
            "addon@karakeep.app" = {
              install_url = "https://addons.mozilla.org/firefox/downloads/file/4477863/karakeep-latest.xpi";
              installation_mode = "force_installed";
            };
            "booru-extension@onelock.org" = {
              install_url = "https://s3.onelock.org/download/extensions/booru-extension.xpi";
              installation_mode = "force_installed";
            };
          };
        };
        profiles.default = {
          isDefault = true;
          mods = [
            "ae7868dc-1fa1-469e-8b89-a5edf7ab1f24" # Load Bar
            "e122b5d9-d385-4bf8-9971-e137809097d0" # No Top Sites
            "e51b85e6-cef5-45d4-9fff-6986637974e1" # smaller zen toast popup
            "b51ff956-6aea-47ab-80c7-d6c047c0d510" # Disable Status Bar
            "ad97bb70-0066-4e42-9b5f-173a5e42c6fc" # SuperPins
            "a6335949-4465-4b71-926c-4a52d34bc9c0" # Better Find Bar
          ];
          settings = {
            "mousebutton.4th.enabled" = false;
            "mousebutton.5th.enabled" = false;
            "zen.welcome-screen.seen" = true;
            "zen.view.experimental-no-window-controls" = true;
            "zen.view.compact.hide-toolbar" = false;
            "zen.view.compact.hide-tabbar" = true;
            "middlemouse.paste" = false;
          };
        };
      };

      hj.packages = [ wrapped ];

      # Write profiles.ini + user.js for each profile
      hj.files =
        let
          profileEntries =
            profilesCfg
            |> lib.attrNames
            |> lib.imap0 (
              i: name:
              let
                profile = profilesCfg.${name};
              in
              [
                "[Profile${toString i}]"
                "Name=${name}"
                "IsRelative=1"
                "Path=${profile.path}"
              ]
              ++ lib.optional profile.isDefault "Default=1"
              |> lib.concatStringsSep "\n"
            );

          defaultPath =
            let
              defaultName =
                profilesCfg
                |> lib.attrNames
                |> (names: lib.findFirst (n: profilesCfg.${n}.isDefault) (lib.head names) names);
            in
            profilesCfg.${defaultName}.path;

          profilesIni =
            [
              ''
                [General]
                StartWithLastProfile=1''
            ]
            ++ profileEntries
            ++ [
              ''
                [Install]
                Default=${defaultPath}''
            ]
            |> lib.concatStringsSep "\n\n"
            |> (s: s + "\n");

          userJsFiles =
            profilesCfg
            |> lib.mapAttrs' (
              name: profile:
              lib.nameValuePair ".config/zen/${profile.path}/user.js" {
                text = mkUserJs profile.settings + "\n";
              }
            );
        in
        {
          ".config/zen/profiles.ini".text = profilesIni;
        }
        // userJsFiles;

      # Default browser via xdg mime
      xdg.mime = lib.mkIf cfg.setAsDefaultBrowser {
        defaultApplications =
          [
            "application/x-extension-shtml"
            "application/x-extension-xhtml"
            "application/x-extension-html"
            "application/x-extension-xht"
            "application/x-extension-htm"
            "x-scheme-handler/unknown"
            "x-scheme-handler/https"
            "x-scheme-handler/http"
            "application/xhtml+xml"
            "application/json"
            "application/pdf"
            "text/html"
          ]
          |> map (mime: lib.nameValuePair mime [ "zen-twilight.desktop" ])
          |> builtins.listToAttrs;
      };

      environment.sessionVariables = lib.mkIf cfg.setAsDefaultBrowser {
        BROWSER = "zen-twilight";
      };

      # Mods activation via system activation script
      system.activationScripts = lib.mkMerge (
        lib.mapAttrsToList (
          name: profile:
          lib.mkIf (profile.mods != [ ]) {
            "zen-mods-${name}" = {
              text = ''
                echo "zen-mods: Updating mods for profile '${name}'..."
                /run/wrappers/bin/su ${self.variables.username} -s /bin/sh -c '${modsActivationScript name profile}'
              '';
              deps = [ "users" ];
            };
          }
        ) profilesCfg
      );
    };

  m.default =
    { lib, ... }:
    {
      options.custom.programs.zen-browser = {
        policies = lib.mkOption {
          type = lib.types.attrs;
          default = { };
          description = "Zen Browser policies.";
        };

        extraPrefs = lib.mkOption {
          type = lib.types.str;
          default = "";
          description = "Extra preferences to include.";
        };

        nativeMessagingHosts = lib.mkOption {
          type = lib.types.listOf lib.types.package;
          default = [ ];
          description = "Native messaging hosts.";
        };

        setAsDefaultBrowser = lib.mkOption {
          type = lib.types.bool;
          default = false;
          description = "Set Zen Browser as default browser.";
        };

        profiles = lib.mkOption {
          default = { };
          type = lib.types.attrsOf (
            lib.types.submodule (
              { name, ... }:
              {
                options = {
                  path = lib.mkOption {
                    type = lib.types.str;
                    default = name;
                    description = "Profile directory name.";
                  };

                  isDefault = lib.mkOption {
                    type = lib.types.bool;
                    default = false;
                    description = "Whether this is the default profile.";
                  };

                  settings = lib.mkOption {
                    type = lib.types.attrs;
                    default = { };
                    description = "Profile settings (written to user.js).";
                  };

                  mods = lib.mkOption {
                    type = lib.types.listOf lib.types.str;
                    default = [ ];
                    description = "List of mod UUIDs from Zen theme store.";
                  };
                };
              }
            )
          );
          description = "Zen Browser profiles.";
        };
      };
    };
}
