# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  go = {
    pname = "go";
    version = "1.26.2";
    src = fetchurl {
      url = "https://go.dev/dl/go1.26.2.src.tar.gz";
      sha256 = "sha256-LpHrtpR6lulDb7KzkmqIAu/mOm03Xf/sT4Kqnb1v1Ds=";
    };
  };
  grubTheme = {
    pname = "grubTheme";
    version = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "grub2-theme";
      rev = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
      fetchSubmodules = false;
      sha256 = "sha256-ChnML4zm4EnVX/WmZW5RWHnK/tqjXSeR4BK8XfN0xxA=";
    };
    date = "2026-01-11";
  };
  kitty = {
    pname = "kitty";
    version = "3e46fa9f81930c595f1a519f4c56c9e77e0e9b79";
    src = fetchFromGitHub {
      owner = "kovidgoyal";
      repo = "kitty";
      rev = "3e46fa9f81930c595f1a519f4c56c9e77e0e9b79";
      fetchSubmodules = false;
      sha256 = "sha256-4HAxZRjdCPvYxD/nNRexjftvDVb9fXMWInrk1wtdjpM=";
    };
    date = "2026-04-26";
  };
}
