# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  grubTheme = {
    pname = "grubTheme";
    version = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "grub2-theme";
      rev = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
      fetchSubmodules = false;
      sha256 = "sha256-ChnML4zm4EnVX/WmZW5RWHnK/tqjXSeR4BK8XfN0xxA=";
    };
    date = "2026-01-11";
  };
}
