# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aemeath-cursor = {
    pname = "aemeath-cursor";
    version = "https://s3.onelock.org/download/cursors/aemeath-cursor.tar.gz";
    src = fetchTarball {
      url = "https://s3.onelock.org/download/cursors/aemeath-cursor.tar.gz";
      sha256 = "sha256-ubr7Zz8m5TFLtrNL8+u1nQjVh5WYG859oOmmXxlWIxI=";
    };
  };
  apple-font = {
    pname = "apple-font";
    version = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
    src = fetchTarball {
      url = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
      sha256 = "sha256-SeTLhl6iFkCDowM87/BTa3mnknngjKpwY89wx8rOQGU=";
    };
  };
  apple-font-emoji = {
    pname = "apple-font-emoji";
    version = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  cliphist = {
    pname = "cliphist";
    version = "25cc3e4affb6d24398cbcb2f42d8e8cf9cf62823";
    src = fetchFromGitHub {
      owner = "sentriz";
      repo = "cliphist";
      rev = "25cc3e4affb6d24398cbcb2f42d8e8cf9cf62823";
      fetchSubmodules = false;
      sha256 = "sha256-1hXxezGSQJ4x1V/iwMZGmB7ONTldpNQ21dbvR1+qkCE=";
    };
    date = "2026-06-08";
  };
  cliphist-tui = {
    pname = "cliphist-tui";
    version = "d9b43bfc88ab50fd49e2dd9237d21343b208357b";
    src = fetchFromGitHub {
      owner = "SHORiN-KiWATA";
      repo = "cliphist-tui";
      rev = "d9b43bfc88ab50fd49e2dd9237d21343b208357b";
      fetchSubmodules = false;
      sha256 = "sha256-TtKy57evRwwS2j0CyB4tsiJZD4fkn0OoYuUkbHWiDS8=";
    };
    date = "2026-06-10";
  };
  confirm-dialog = {
    pname = "confirm-dialog";
    version = "0231323227dc97b1a4f070f4b8bf8c37d538a6df";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "confirm-dialog.yazi";
      rev = "0231323227dc97b1a4f070f4b8bf8c37d538a6df";
      fetchSubmodules = false;
      sha256 = "sha256-3KxK0cTjm9z+ilXhBFbvWyZmWVfiaJKKIpbVcEABjYE=";
    };
    date = "2026-05-25";
  };
  extra-metadata = {
    pname = "extra-metadata";
    version = "044274ca2e473f18910d03ca7392dff5ef028deb";
    src = fetchFromGitHub {
      owner = "boydaihungst";
      repo = "file-extra-metadata.yazi";
      rev = "044274ca2e473f18910d03ca7392dff5ef028deb";
      fetchSubmodules = false;
      sha256 = "sha256-Yq8nv/MSxOy0xTyeIQac/Gu8j1tLL6m7glFicjJ3fIs=";
    };
    date = "2026-04-22";
  };
  fsel = {
    pname = "fsel";
    version = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
    src = fetchFromGitHub {
      owner = "Mjoyufull";
      repo = "fsel";
      rev = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
      fetchSubmodules = false;
      sha256 = "sha256-7YoRc6jOuQUI0yv3qBHFhc60G/RG0LwVsKkN90UkPn4=";
    };
    date = "2026-05-17";
  };
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "7be2437b45be1da9b3be0ed2f244709c9b9be242";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "7be2437b45be1da9b3be0ed2f244709c9b9be242";
      fetchSubmodules = false;
      sha256 = "sha256-vW6o5vbYXr++cFAcyvl7E2tYHQMV5lGK2rEOG5iiRPg=";
    };
    date = "2026-05-25";
  };
  no-header-prompt = {
    pname = "no-header-prompt";
    version = "dd34339092b7cdc1f8213017f939e55e0b47a008";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "no-header-prompt.yazi";
      rev = "dd34339092b7cdc1f8213017f939e55e0b47a008";
      fetchSubmodules = false;
      sha256 = "sha256-dHJNk3o9vMGUnO/KAl7R6UdEq1giyp2DNXzxmAKBZP0=";
    };
    date = "2026-05-25";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "764a38d1de308da3268222692652a0a85bb71eee";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "764a38d1de308da3268222692652a0a85bb71eee";
      fetchSubmodules = false;
      sha256 = "sha256-vlNT2248Oxg3++bk8ZkozsU4wDbxOkh6dl3GeoBmmXE=";
    };
    date = "2026-06-09";
  };
  tmuxFloax = {
    pname = "tmuxFloax";
    version = "133f526793d90d2caa323c47687dd5544a2c704b";
    src = fetchFromGitHub {
      owner = "omerxx";
      repo = "tmux-floax";
      rev = "133f526793d90d2caa323c47687dd5544a2c704b";
      fetchSubmodules = false;
      sha256 = "sha256-9Hb9dn2qHF6KcIhtogvycX3Z0MoQrLPLCzZXtjGlPHw=";
    };
    date = "2026-02-24";
  };
  yaziline = {
    pname = "yaziline";
    version = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
    src = fetchFromGitHub {
      owner = "llanosrocas";
      repo = "yaziline.yazi";
      rev = "25161c18e61339b6a79f29f8948e3c360e3f9ace";
      fetchSubmodules = false;
      sha256 = "sha256-gF21K8Sn9VFh6nKcM5dhTiAH1sOE9D/Gmc8i3J8m+S4=";
    };
    date = "2026-05-09";
  };
}
