# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  aemeath-cursor = {
    pname = "aemeath-cursor";
    version = "https://s3.onelock.org/download/cursors/aemeath-cursor.tar.gz";
    src = fetchTarball {
      url = "https://s3.onelock.org/download/cursors/aemeath-cursor.tar.gz";
      sha256 = "sha256-ubr7Zz8m5TFLtrNL8+u1nQjVh5WYG859oOmmXxlWIxI=";
    };
  };
  apple-font = {
    pname = "apple-font";
    version = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
    src = fetchTarball {
      url = "https://s3.onelock.org/download/fonts/apple-nerd.tar.gz";
      sha256 = "sha256-SeTLhl6iFkCDowM87/BTa3mnknngjKpwY89wx8rOQGU=";
    };
  };
  apple-font-emoji = {
    pname = "apple-font-emoji";
    version = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
    src = fetchurl {
      url = "https://github.com/samuelngs/apple-emoji-linux/releases/latest/download/AppleColorEmoji-Linux.ttf";
      sha256 = "sha256-U1oEOvBHBtJEcQWeZHRb/IDWYXraLuo0NdxWINwPUxg=";
    };
  };
  cliphist = {
    pname = "cliphist";
    version = "980c85fab4a5bab04c6f14bed49b330fd18922ab";
    src = fetchFromGitHub {
      owner = "sentriz";
      repo = "cliphist";
      rev = "980c85fab4a5bab04c6f14bed49b330fd18922ab";
      fetchSubmodules = false;
      sha256 = "sha256-EeBIGhbWGw6BZ54kG9BhBc5OQGy3Ag/7eyXRImovqi8=";
    };
    date = "2026-04-21";
  };
  cliphist-tui = {
    pname = "cliphist-tui";
    version = "fd4a47baaba60598603d6c760512d2169479872b";
    src = fetchFromGitHub {
      owner = "SHORiN-KiWATA";
      repo = "cliphist-tui";
      rev = "fd4a47baaba60598603d6c760512d2169479872b";
      fetchSubmodules = false;
      sha256 = "sha256-wjgE9aladixbGfMXVdkvxEBJHKS2BEepbwILZro7d0A=";
    };
    date = "2026-04-26";
  };
  fsel = {
    pname = "fsel";
    version = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
    src = fetchFromGitHub {
      owner = "Mjoyufull";
      repo = "fsel";
      rev = "6b6ae52e3a2c254007e8a2c332a8d5de99428ba5";
      fetchSubmodules = false;
      sha256 = "sha256-7YoRc6jOuQUI0yv3qBHFhc60G/RG0LwVsKkN90UkPn4=";
    };
    date = "2026-05-17";
  };
  fuzzy-search = {
    pname = "fuzzy-search";
    version = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "fuzzy-search.yazi";
      rev = "16cea088a39c7769fbd22c4810347b04dd38c6b2";
      fetchSubmodules = false;
      sha256 = "sha256-3YsZQ7SOkJZfUWP2KGzp8fPpT42M+x2aThs/AYmdy0o=";
    };
    date = "2026-03-25";
  };
  grubTheme = {
    pname = "grubTheme";
    version = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
    src = fetchFromGitHub {
      owner = "onelocked";
      repo = "grub2-theme";
      rev = "207dfe09411f08916666acf65bf6262e5ef5e6d0";
      fetchSubmodules = false;
      sha256 = "sha256-ChnML4zm4EnVX/WmZW5RWHnK/tqjXSeR4BK8XfN0xxA=";
    };
    date = "2026-01-11";
  };
  otter-launcher = {
    pname = "otter-launcher";
    version = "380ceb9d2cf9b02854fbd3be39177e5e151fae6c";
    src = fetchFromGitHub {
      owner = "kuokuo123";
      repo = "otter-launcher";
      rev = "380ceb9d2cf9b02854fbd3be39177e5e151fae6c";
      fetchSubmodules = false;
      sha256 = "sha256-oQw4/UqDpE/K0lkc+zFXdWsNKps9p0rZg6ybMwVDhsM=";
    };
    date = "2026-05-17";
  };
  tmuxFloax = {
    pname = "tmuxFloax";
    version = "133f526793d90d2caa323c47687dd5544a2c704b";
    src = fetchFromGitHub {
      owner = "omerxx";
      repo = "tmux-floax";
      rev = "133f526793d90d2caa323c47687dd5544a2c704b";
      fetchSubmodules = false;
      sha256 = "sha256-9Hb9dn2qHF6KcIhtogvycX3Z0MoQrLPLCzZXtjGlPHw=";
    };
    date = "2026-02-24";
  };
  zen-theme-store = {
    pname = "zen-theme-store";
    version = "7173dba5d060417fd65764b706856ae609496e31";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "theme-store";
      rev = "7173dba5d060417fd65764b706856ae609496e31";
      fetchSubmodules = false;
      sha256 = "sha256-Vq0AboLzase+tTZ1Erf2cKpF55cm3eHNuXmmQuOknvw=";
    };
    date = "2026-03-11";
  };
}
